language: python

services:
  - docker

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose && sudo chmod +x /usr/bin/docker-compose
  - sudo docker-compose build --pull
  - mkdir $HOME/.aws
  - touch $HOME/empty.json

install:
  - pip install -r requirements-test.txt

script:
  - make test
  - sudo PASS=testing GOOGLE_APPLICATION_CREDENTIALS=/dummy OS_CACERT=/dummy2 docker-compose up -d
  - sh -c 'sleep 10; test "$(curl -4k -u test:testing https://localhost:8443/test)" = "OK"'
