language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements-test.txt
script:
  - flake8 --ignore=E501,W504
  - pylint --errors-only $(find . -name \*.py)
