version: '2.1'

services:
  app:
    build: .
    command: --status all --sort time --port 7777
    environment:
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - AZURE_SUBSCRIPTION_ID
      - AZURE_TENANT_ID
      - GOOGLE_APPLICATION_CREDENTIALS
      - TZ=Europe/Berlin
    volumes:
      - ~/.aws:/root/.aws:ro
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}:ro
    read_only: true
    restart: always
  nginx:
    build: nginx
    environment:
      - APP_PORT=7777
      - NGINX_HOST=ricardox.suse.de
    ports:
      - "8443:443"
    volumes:
      - ~/TLS:/etc/nginx/ssl:ro
    read_only: true
    restart: always
